### ISSUE TITLE
Add Healthcheck

### ISSUE THREAD

**Issue by martindsouza** [fuzziebrain/docker-oracle-xe#2]
See https://github.com/oraclebase/dockerfiles/blob/master/database/ol7_183/scripts/healthcheck.sh as an example and `Dockerfile` config would look like: `HEALTHCHECK --start-period=10s --interval=5s --retries=5 CMD curl --fail http://localhost:8080/ords || exit 1`

From the sample `healthcheck.sh` need to find a way to login to dB without password.

**Comment by martindsouza** [comment]
@fuzziebrain  can you please look into the current healthcheck file as it's not working

**Comment by fuzziebrain** [comment]
Should be working now. Let me know otherwise.
