### ISSUE TITLE
Cannot alter password for XE/XEPDB1

### ISSUE THREAD

**Issue by demonguru18** [fuzziebrain/docker-oracle-xe#26]
The installation is very unclear, I was able install 18c on Container. But I cannot connect with SQL Develop Application to the database. I tried to change the password for sys (password will change but every-time I get same error invalid login info on sql developer).
I used this command on docker exec
sqlcl sys/Oracle18@localhost:32118/XEPDB2 as sysdba
SQL> Then used the Alter command to change password for sys
Password changes but cannot login.

**Comment by fuzziebrain** [comment]
How did you end up with the PDB named XEPDB2?

**Comment by demonguru18** [comment]
sorry it is XEPDB1

**Comment by demonguru18** [comment]
I am able to change the password by exec docker sh via kitematic, no error when changing password, but i cannot login with same password. I tried to re create the password file still no success.
I used this command to crete pwd file
![image](https://user-images.githubusercontent.com/4347612/50582422-77a48300-0e30-11e9-9542-e3c0c24ea46c.png)

**Comment by demonguru18** [comment]
I solved this issue by adding a password option to the docker run command. Also made a step by step guide to install this using your build and tagged you in the video. Thanks for you help once again.
https://www.youtube.com/watch?v=CbopSCwATIg

**Comment by fuzziebrain** [comment]
Thanks for the video. We appreciate the credits. I'd appreciate that you'd also include @martindsouza who contributed quite a bit to this project. With regards to your issues changing the SYS password, please login to the root container before attempting to do so.
