### ISSUE TITLE
The SID of the plugable Database is not known to SQL Developer.

### ISSUE THREAD

**Issue by debecylinder** [fuzziebrain/docker-oracle-xe#37]
I receive the following error:

Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

I can connect to the SID of XE with SQL Developer though. Also I can connect to the XEPDB1 and XEPDB2 by the comand line like stated in the example:

$ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/XEPDB1 as sysdba

I restarted SQL-Developer and the container. It didn 't help. 

Note: The only change I made was to map the ports directly -p 1521:1521

- - - 
My specs:
Linux Mint 19.1 Cinnamon
Kernel: 4.15.0-20-generic

docker version

Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false

SQL-Developer:
Version 19.1.0.094

Git branch: Master

**Comment by fuzziebrain** [comment]
@debecylinder use Service Name XEPDB1

**Comment by debecylinder** [comment]
That worked! Thank you a lot! Service Name instead of SID that did the trick.
